// SPDX-FileCopyrightText: 2026 Nikolay Govorov
// SPDX-License-Identifier: AGPL-3.0-or-later

use maud::{DOCTYPE, Markup, html};

#[derive(Clone)]
pub struct Context {
    pub repositories: &'static str,
    pub root_title: std::sync::Arc<str>,
    pub root_description: std::sync::Arc<str>,
    pub clone_prefix: std::sync::Arc<str>,
}

#[derive(Clone, Copy, Eq, PartialEq)]
pub enum Page {
    About,
    Summary,
    Refs,
    Log,
    Tree,
    Revision,
    Diff,
    Stats,
}

pub fn render(
    context: &Context,
    repository: &crate::models::repository::Info,
    revision: &str,
    active: Page,
    content: Markup,
    method: &axum::http::Method,
) -> axum::response::Response {
    render_titled(context, repository, revision, active, None, content, method)
}

pub fn render_titled(
    context: &Context,
    repository: &crate::models::repository::Info,
    revision: &str,
    active: Page,
    page_title: Option<&str>,
    content: Markup,
    method: &axum::http::Method,
) -> axum::response::Response {
    let repo = repository_url(&repository.name);
    let rev = encode_path(revision);
    let title = page_title.map_or_else(
        || format!("{} - {}", repository.name, repository.description),
        |page_title| {
            format!(
                "{page_title} - {} - {}",
                repository.name, repository.description
            )
        },
    );
    let document = html! {
        (DOCTYPE)
        html lang="en" {
            head {
                title { (title) }
                meta name="generator" content="Gilti";
                meta name="robots" content="index, nofollow";
                link rel="stylesheet" type="text/css" href="/-/assets/gilti.css";
                script type="text/javascript" src="/-/assets/gilti.js" {}
                link rel="shortcut icon" href="/-/assets/favicon.ico";
            }
            body { div id="gilti" {
                table id="header" {
                    tr {
                        td class="logo" rowspan="2" { a href="/" { img src="/-/assets/gilti.png" alt="gilti logo"; } }
                        td class="main" { (&*context.root_title) " : " a href=(&repo) { (&repository.name) } }
                    }
                    tr { td class="sub" { (&repository.description) } }
                }
                table class="tabs" { tr { td {
                    @if repository.has_readme {
                        (tab(&format!("{repo}/+/about"), "about", active == Page::About))
                    }
                    (tab(&repo, "summary", active == Page::Summary))
                    (tab(&format!("{repo}/+/refs"), "refs", active == Page::Refs))
                    (tab(&format!("{repo}/+/{rev}/+/log"), "log", active == Page::Log))
                    (tab(&format!("{repo}/+/{rev}/+/tree"), "tree", active == Page::Tree))
                    (tab(&format!("{repo}/+/{rev}"), "commit", active == Page::Revision))
                    (tab(&format!("{repo}/+/diff/HEAD..{rev}"), "diff", active == Page::Diff))
                    (tab(&format!("{repo}/+/stats"), "stats", active == Page::Stats))
                } } }
                div class="content" { (content) }
                div class="footer" { "generated by Gilti" }
            } }
        }
    }
    .into_string();
    let length = document.len();
    let body = if method == axum::http::Method::HEAD {
        axum::body::Body::empty()
    } else {
        axum::body::Body::from(document)
    };
    axum::response::Response::builder()
        .status(axum::http::StatusCode::OK)
        .header(axum::http::header::CONTENT_TYPE, "text/html; charset=UTF-8")
        .header(axum::http::header::CONTENT_LENGTH, length)
        .body(body)
        .expect("HTML response is valid")
}

fn tab(url: &str, label: &str, active: bool) -> Markup {
    html! { a href=(url) class=[active.then_some("active")] { (label) } }
}

pub fn repository_url(repository: &str) -> String {
    format!("/{}", encode_path(repository))
}

pub fn encode_path(value: &str) -> String {
    let mut encoded = String::new();
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric() || byte == b'/' || byte == b'_' {
            encoded.push(char::from(byte));
        } else {
            use std::fmt::Write;
            write!(encoded, "%{byte:02x}").expect("writing to String cannot fail");
        }
    }
    encoded
}

pub fn age(timestamp: i64) -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |duration| duration.as_secs() as i64);
    let seconds = now.saturating_sub(timestamp).max(0);
    let (amount, unit) = if seconds < 120 * 60 {
        (seconds / 60, "min.")
    } else if seconds < 48 * 60 * 60 {
        (seconds / (60 * 60), "hours")
    } else if seconds < 14 * 24 * 60 * 60 {
        (seconds / (24 * 60 * 60), "days")
    } else if seconds < 60 * 24 * 60 * 60 {
        (seconds / (7 * 24 * 60 * 60), "weeks")
    } else if seconds < 730 * 24 * 60 * 60 {
        (seconds / (30 * 24 * 60 * 60), "months")
    } else {
        (seconds / (365 * 24 * 60 * 60), "years")
    };
    format!("{amount} {unit} ago")
}
