// SPDX-FileCopyrightText: 2026 Nikolay Govorov
// SPDX-License-Identifier: AGPL-3.0-or-later

use maud::{Markup, Render, html};

use crate::styles::classes::layout;

pub struct NestedLink<'a> {
    pub url: &'a str,
    pub label: &'a str,
}

#[derive(Clone)]
pub struct NavigationLink<'a> {
    pub url: &'a str,
    pub label: &'a str,
    pub active: bool,
}

pub struct Layout<'a> {
    pub root_title: &'a str,
    pub description: &'a str,
    pub nested_links: Vec<NestedLink<'a>>,
    pub navigation_links: Vec<NavigationLink<'a>>,
    pub navigation_search: Option<Markup>,
    pub sidebar: Option<Markup>,
    pub content: Markup,
}

impl Render for Layout<'_> {
    fn render(&self) -> Markup {
        html! {
            div class=(layout::ROOT) {
                header class=(layout::HEADER) {
                    a class=(layout::LOGO) href="/" {
                        img src=(dimidiumlabs_ui::FAVICON_SVG_PATH) alt="gilti logo";
                    }
                    h1 class=(layout::TITLE) {
                        (self.root_title)
                        @for link in &self.nested_links {
                            " : " a href=(link.url) { (link.label) }
                        }
                    }
                    div class=(layout::DESCRIPTION) { (self.description) }
                }

                div class=(layout::NAVIGATION) {
                    nav {
                        @for link in &self.navigation_links {
                            a href=(link.url) class=(layout::NAVIGATION_LINK) data-active=(link.active) {
                                (link.label)
                            }
                        }
                    }

                    @if let Some(search) = &self.navigation_search {
                        div class=(layout::NAVIGATION_SEARCH) { (search) }
                    }
                }

                main class=(layout::CONTENT) {
                    @if let Some(sidebar) = &self.sidebar {
                        aside class=(layout::SIDEBAR) { (sidebar) }
                    }
                    (&self.content)
                }

                footer class=(layout::FOOTER) { "Generated by Gilti" }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use maud::{Render, html};

    use super::{Layout, NavigationLink, NestedLink};

    #[test]
    fn owns_the_complete_application_shell() {
        let rendered = Layout {
            root_title: "Gilti",
            description: "Git server",
            nested_links: vec![NestedLink {
                url: "/project",
                label: "project",
            }],
            navigation_links: vec![NavigationLink {
                url: "/project/+/log",
                label: "log",
                active: true,
            }],
            navigation_search: Some(html! { form { "search" } }),
            sidebar: Some(html! { form { "options" } }),
            content: html! { p { "content" } },
        }
        .render()
        .into_string();

        for expected in [
            "<div class=",
            "<h1 class=",
            "href=\"/project\"",
            "href=\"/project/+/log\"",
            "<form>search</form>",
            "<aside class=",
            "<form>options</form>",
            "content",
            "Generated by Gilti",
        ] {
            assert!(
                rendered.contains(expected),
                "missing {expected}: {rendered}"
            );
        }
    }
}
