# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
publish = false
edition = "2024"
version = "0.1.0"
license = "AGPL-3.0-or-later"
authors = ["Nikolay Govorov <me@govorov.online>"]
homepage = "https://github.com/dimidiumlabs/gilti"
repository = "https://github.com/dimidiumlabs/gilti"

[workspace.dependencies]
axum = { version = "0.8.4", default-features = false, features = ["http1", "tokio"] }
libc = "0.2.172"
percent-encoding = "2.3.2"
tokio = { version = "1.44.2", features = ["io-util", "macros", "net", "process", "rt-multi-thread", "signal"] }
tower = { version = "0.5.2", features = ["util"] }

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = true
