# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = "2026.7.5"

[settings]
experimental = true

[tools]
"github:EmbarkStudios/cargo-about" = "0.8.4"
helm = "4.1.1"
rust = { version = "1.97.1", profile = "minimal", components = ["clippy", "llvm-tools-preview", "rustfmt"] }
shellcheck = "0.11.0"

[task_config]
dir = "{{cwd}}"
includes = [
  "git::https://git.dimidiumlabs.io/platform.git//tasks?ref=14b537a5d8373d8cdd1ad8dd5248e1f3f6a5147b",
]
