# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "gilti-ssh"
description = "Restricted SSH command for Gilti Git access"
version.workspace = true

repository.workspace = true
homepage.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
libc.workspace = true
