# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "gilti"
description = "Gilti daemon"
version.workspace = true

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[build-dependencies]
dimidiumlabs-ui-build = { git = "https://git.dimidiumlabs.io/platform.git", rev = "e6b7becea47feec6188ebcfd2cec179762be4b2d" }

[dependencies]
dimidiumlabs-ui = { git = "https://git.dimidiumlabs.io/platform.git", rev = "e6b7becea47feec6188ebcfd2cec179762be4b2d" }
dimidiumlabs-server = { git = "https://git.dimidiumlabs.io/platform.git", rev = "e6b7becea47feec6188ebcfd2cec179762be4b2d" }

axum.workspace = true
libc.workspace = true
percent-encoding.workspace = true
pulldown-cmark.workspace = true
tokio.workspace = true
tower.workspace = true
maud.workspace = true
serde.workspace = true
serde_json.workspace = true
gilti-git = { path = "../git" }
tokio-util.workspace = true
futures-util.workspace = true
hyper-util.workspace = true
